---
- name: vm_create
  hosts: PE
  tasks:
  - import_role:
     name: vm_create
  vars_files:
  - required_vars.yml

- name: Prep VMs
  hosts: k8s_vms
  tasks:
  - import_role:
     name: k8s_vm_prep
 

- name: Creating K8s inventory file for kubespray
  hosts: PE
  tasks:
  - import_role:
     name: k8s_inventory_init
