# Copyright 2019 Nutanix Inc
#
# example usage: kubectl create -f <this_file>

---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-node-ntnx-plugin
  namespace: ntnx-system
spec:
  selector:
    matchLabels:
      app: csi-node-ntnx-plugin
  template:
    metadata:
      labels:
        app: csi-node-ntnx-plugin
    spec:
      serviceAccount: csi-node-ntnx-plugin
      hostNetwork: true
      containers:
        - name: driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.2.0
          args:
          - "--v=5"
          - "--csi-address=$(ADDRESS)"
          - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/nutanix/var/lib/kubelet/plugins/com.nutanix.csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi/
            - name: registration-dir
              mountPath: /registration
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
        - name: csi-node-ntnx-plugin 
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          image: ntnx/ntnx-csi:v2.0.0
          args:
            - --endpoint=$(CSI_ENDPOINT)
            - --nodeid=$(NODE_ID)
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: pods-mount-dir
              mountPath: /var/nutanix/var/lib/kubelet
              mountPropagation: "Bidirectional"
            - mountPath: /dev
              name: device-dir
            - mountPath: /etc/iscsi
              name: iscsi-dir
            - mountPath: /sbin/iscsiadm
              name: iscsiadm
            - mountPath: /lib/modules
              name: lib-dir
          ports:
            - containerPort: 9808
              name: healthz
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 2
            failureThreshold: 3
        - name: liveness-probe
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /csi
              name: plugin-dir
          image: quay.io/k8scsi/livenessprobe:v1.1.0
          args:
            - --csi-address=/csi/csi.sock
      volumes:
      - hostPath:
          path: /var/nutanix/var/lib/kubelet/plugins_registry/
          type: Directory
        name: registration-dir
      - hostPath:
          path: /var/nutanix/var/lib/kubelet/plugins/com.nutanix.csi/
          type: DirectoryOrCreate
        name: plugin-dir
      - hostPath:
          path: /var/nutanix/var/lib/kubelet
          type: Directory
        name: pods-mount-dir
      - hostPath:
          path: /dev
        name: device-dir
      - hostPath:
          path: /etc/iscsi
          type: Directory
        name: iscsi-dir
      - hostPath:
          path: /sbin/iscsiadm
          type: File
        name: iscsiadm
      - hostPath:
          path: /lib/modules
          type: Directory
        name: lib-dir
